In [2]:
import numpy as np

val= np.array([1,2,3,4,5,5])
# print(val.dtype)

# val=np.insert(val,2,23)

# val=np.append(val,34)
# print(val)

# for i in val:
#   print(i, end=" ")

copyArray = [int(x) for x in val]
print(copyArray)

[1, 2, 3, 4, 5, 5]


In [3]:
arr= np.array([])

n= int(input("enter array size"))

for i in range(0, n):
  value= int(input("enter next element "))
  arr=np.append(arr, value)

print("filled the empty array")
for x in arr:
  print(int(x), end=" ")

filled the empty array
2 2 

In [10]:
# one dimentional array

zero= np.zeros(5)
print(zero)

[0. 0. 0. 0. 0.]


In [9]:
# two dimentionall

two= np.array([
   [1,2,3,4,4],
    [5,6,7,8,9],
     [1,2,3,4,4],
   
  ])
print(two)


[[1 2 3 4 4]
 [5 6 7 8 9]
 [1 2 3 4 4]]


In [ ]:
# three dimentional

three = np.array([[
  [1,2,3,4,4],
    [5,6,7,8,9]
],
[
  [1,2,3,4,4],
    [5,6,7,8,9]
]
])

# on the even no replace from the 0
three[three%2==0]=0

three.sort()
print(three)

#  it convert 2d array in one dimention array
three.flatten()

for i in three:
  for j in i:

  if (i==j)

# for block in three:
#   for row in block:
#     for element in row:
#       if (element %2==0):
#         three.replace(element,0)
      



[[[0 0 0 1 3]
  [0 0 5 7 9]]

 [[0 0 0 1 3]
  [0 0 5 7 9]]]


array([0, 0, 0, 1, 3, 0, 0, 5, 7, 9, 0, 0, 0, 1, 3, 0, 0, 5, 7, 9])